# Generated by Django 2.0 on 2021-09-05 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=254, verbose_name='Descripción')),
                ('album_url', models.CharField(max_length=254)),
                ('ubicacion', models.CharField(max_length=254, verbose_name='Ubicacion')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paises.Ciudad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
