# Generated by Django 2.0 on 2021-09-14 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitios', '0003_auto_20210909_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=254, verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puntuacion', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='sitio',
            name='tipo',
            field=models.CharField(choices=[('finca', 'Finca'), ('centro_recreacional', 'Centro Recreacional'), ('parque', 'Parque')], default='nn', max_length=100, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='album_url',
            field=models.ImageField(null=True, upload_to='sitios', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitios.sitio'),
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitios.sitio'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
